# Generated by Django 3.1.1 on 2020-12-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sub',
        ),
    ]
