# Generated by Django 3.1.1 on 2020-12-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationPage', '0002_remove_course_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirments',
            name='cs2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='cs3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='cs4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='pr1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='pr2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='pr3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='pr4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='pr5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
